#config.yml
team_path: https://www.fangraphs.com/depthcharts.aspx?position=Standings
roster_path: https://www.fangraphs.com/teams/
database:
  host: host_name
  schema: schema_name 
  user: user_name
  pass: #keyring
  port: port_number

